export const songCatalog = [
  {
    id: "sunny",
    title: "晴天",
    artist: "周杰伦",
    album: "叶惠美",
    bpm: 92,
    energy: 64,
    valence: 72,
    coverUrl: "./picture/Mini Player/Cover.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "qq-demo-sunny",
    copyright: "demo-metadata-only",
    tags: ["通勤", "轻快", "怀念", "人声", "城市感"],
    scenes: ["commute", "photo-city"],
    moods: ["轻快陪伴", "晴朗"]
  },
  {
    id: "slow-love",
    title: "慢慢喜欢你",
    artist: "莫文蔚",
    album: "如果没有你",
    bpm: 74,
    energy: 38,
    valence: 58,
    coverUrl: "./picture/mood-4.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "qq-demo-slow-love",
    copyright: "demo-metadata-only",
    tags: ["治愈", "雨天", "低噪", "人声", "温柔"],
    scenes: ["heal", "photo-rain"],
    moods: ["安静治愈", "柔和"]
  },
  {
    id: "free",
    title: "想自由",
    artist: "林宥嘉",
    album: "大小说家",
    bpm: 82,
    energy: 42,
    valence: 46,
    coverUrl: "./picture/mood-2.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "qq-demo-free",
    copyright: "demo-metadata-only",
    tags: ["放空", "低能量", "夜晚", "独处", "人声"],
    scenes: ["focus", "heal"],
    moods: ["稳定专注", "放空"]
  },
  {
    id: "everyday",
    title: "Everyday",
    artist: "Ariana Grande",
    album: "Dangerous Woman",
    bpm: 126,
    energy: 88,
    valence: 82,
    coverUrl: "./picture/mood-1.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "qq-demo-everyday",
    copyright: "demo-metadata-only",
    tags: ["运动", "高能", "律动", "提神", "电子流行"],
    scenes: ["energy"],
    moods: ["元气释放", "提神"]
  },
  {
    id: "city-lights",
    title: "City Lights",
    artist: "Morning Tape",
    album: "Urban Focus",
    bpm: 86,
    energy: 52,
    valence: 62,
    coverUrl: "./picture/mood-3.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-city-lights",
    copyright: "demo-safe",
    tags: ["通勤", "Lo-fi", "城市感", "低干扰", "专注"],
    scenes: ["commute", "focus"],
    moods: ["稳定专注", "轻快陪伴"]
  },
  {
    id: "rain-window",
    title: "Rain Window",
    artist: "Soul Soother",
    album: "Soft Weather",
    bpm: 70,
    energy: 32,
    valence: 54,
    coverUrl: "./picture/mood-5.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-rain-window",
    copyright: "demo-safe",
    tags: ["雨天", "治愈", "低噪", "氛围", "睡前"],
    scenes: ["heal", "photo-rain"],
    moods: ["安静治愈"]
  },
  {
    id: "metro-breath",
    title: "Metro Breath",
    artist: "City Loops",
    album: "Commute Sketches",
    bpm: 96,
    energy: 58,
    valence: 65,
    coverUrl: "./picture/City haze.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-metro-breath",
    copyright: "demo-safe",
    tags: ["通勤", "城市感", "轻快", "低干扰", "电子"],
    scenes: ["commute", "photo-city"],
    moods: ["轻快陪伴"]
  },
  {
    id: "window-seat",
    title: "Window Seat",
    artist: "Soft Transit",
    album: "On The Way",
    bpm: 88,
    energy: 48,
    valence: 60,
    coverUrl: "./picture/Change Image Here-1.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-window-seat",
    copyright: "demo-safe",
    tags: ["通勤", "人声", "城市感", "温柔", "陪伴"],
    scenes: ["commute", "heal"],
    moods: ["轻快陪伴", "安静治愈"]
  },
  {
    id: "green-walk",
    title: "Green Walk",
    artist: "Fresh Pulse",
    album: "Morning Steps",
    bpm: 108,
    energy: 72,
    valence: 78,
    coverUrl: "./picture/mood-1.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-green-walk",
    copyright: "demo-safe",
    tags: ["清晨", "提神", "轻快", "户外", "流行"],
    scenes: ["commute", "energy"],
    moods: ["轻快陪伴", "元气释放"]
  },
  {
    id: "study-lamp",
    title: "Study Lamp",
    artist: "Lo Room",
    album: "Quiet Tasks",
    bpm: 78,
    energy: 34,
    valence: 50,
    coverUrl: "./picture/mood-2.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-study-lamp",
    copyright: "demo-safe",
    tags: ["专注", "Lo-fi", "低干扰", "室内", "学习"],
    scenes: ["focus"],
    moods: ["稳定专注"]
  },
  {
    id: "deep-page",
    title: "Deep Page",
    artist: "Focus Field",
    album: "One More Hour",
    bpm: 84,
    energy: 44,
    valence: 55,
    coverUrl: "./picture/mood-3.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-deep-page",
    copyright: "demo-safe",
    tags: ["专注", "低干扰", "氛围", "阅读", "无强人声"],
    scenes: ["focus"],
    moods: ["稳定专注"]
  },
  {
    id: "night-blanket",
    title: "Night Blanket",
    artist: "Warm Noise",
    album: "After 10 PM",
    bpm: 66,
    energy: 24,
    valence: 48,
    coverUrl: "./picture/mood-5.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-night-blanket",
    copyright: "demo-safe",
    tags: ["夜晚", "睡前", "低噪", "治愈", "独处"],
    scenes: ["heal"],
    moods: ["安静治愈", "放空"]
  },
  {
    id: "after-rain",
    title: "After Rain",
    artist: "Misty Tape",
    album: "Wet Streets",
    bpm: 76,
    energy: 36,
    valence: 57,
    coverUrl: "./picture/Photo/City haze.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-after-rain",
    copyright: "demo-safe",
    tags: ["雨天", "治愈", "城市感", "低噪", "人声"],
    scenes: ["photo-rain", "heal"],
    moods: ["安静治愈"]
  },
  {
    id: "heartbeat-run",
    title: "Heartbeat Run",
    artist: "Motion Club",
    album: "Move Mode",
    bpm: 132,
    energy: 94,
    valence: 84,
    coverUrl: "./picture/mood-1.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-heartbeat-run",
    copyright: "demo-safe",
    tags: ["运动", "高能", "律动", "跑步", "强鼓点"],
    scenes: ["energy"],
    moods: ["元气释放"]
  },
  {
    id: "bright-jump",
    title: "Bright Jump",
    artist: "Pop Circuit",
    album: "Good Charge",
    bpm: 120,
    energy: 86,
    valence: 88,
    coverUrl: "./picture/mood-4.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-bright-jump",
    copyright: "demo-safe",
    tags: ["提神", "高能", "流行", "律动", "开心"],
    scenes: ["energy", "commute"],
    moods: ["元气释放"]
  },
  {
    id: "friend-signal",
    title: "Friend Signal",
    artist: "Weekend Chat",
    album: "Share The Song",
    bpm: 102,
    energy: 66,
    valence: 80,
    coverUrl: "./picture/mood-3.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-friend-signal",
    copyright: "demo-safe",
    tags: ["社交", "分享", "轻快", "流行", "陪伴"],
    scenes: ["commute", "energy"],
    moods: ["轻快陪伴"]
  },
  {
    id: "blue-hour",
    title: "Blue Hour",
    artist: "Low Skyline",
    album: "Evening Window",
    bpm: 72,
    energy: 30,
    valence: 44,
    coverUrl: "./picture/City haze-1.png",
    previewUrl: "",
    platform: "local-demo",
    platformSongId: "local-blue-hour",
    copyright: "demo-safe",
    tags: ["夜晚", "低能量", "城市感", "放空", "氛围"],
    scenes: ["heal", "photo-rain"],
    moods: ["放空", "安静治愈"]
  }
];

export const scenePresets = {
  commute: {
    label: "通勤路上",
    visualSignals: ["城市街景", "移动状态", "白天自然光"],
    emotion: "轻微疲惫但希望被提亮",
    tags: ["通勤", "轻快", "陪伴"],
    avoidTags: ["重鼓点", "过强电子"],
    bpmRange: [82, 105]
  },
  heal: {
    label: "雨天放松",
    visualSignals: ["低饱和色彩", "雨后环境", "安静空间"],
    emotion: "安静、放松、需要治愈",
    tags: ["治愈", "雨天", "低噪"],
    avoidTags: ["高燃", "强刺激"],
    bpmRange: [68, 88]
  },
  focus: {
    label: "学习专注",
    visualSignals: ["桌面", "室内", "稳定光线"],
    emotion: "需要低干扰和稳定节奏",
    tags: ["专注", "Lo-fi", "低干扰"],
    avoidTags: ["强人声", "高情绪起伏"],
    bpmRange: [76, 92]
  },
  energy: {
    label: "运动提神",
    visualSignals: ["运动状态", "高能量", "明亮环境"],
    emotion: "想要被节奏推动",
    tags: ["运动", "高能", "律动"],
    avoidTags: ["低能量", "睡前"],
    bpmRange: [112, 132]
  },
  "photo-rain": {
    label: "照片：雨后城市",
    visualSignals: ["雨后城市", "冷色光线", "通勤路面"],
    emotion: "安静、轻微疲惫",
    tags: ["雨天", "治愈", "通勤", "低噪"],
    avoidTags: ["高燃", "重鼓点"],
    bpmRange: [70, 95]
  }
};
